# Generated by Django 3.1.1 on 2020-09-02 14:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('aadhar', models.IntegerField(unique=True)),
                ('pan', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('Phone', models.IntegerField(unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='LoanAccount',
            fields=[
                ('loan_no', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('loan_type', models.CharField(choices=[('PRS', 'Personal Loan'), ('HOU', 'Housing Loan'), ('MRT', 'Mortgage Loan'), ('GLD', 'Gold Loan')], max_length=3)),
                ('loan_amount_issued', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'ordering': ['loan_no'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this customer across the whole bank.', primary_key=True, serialize=False)),
                ('account_no', models.IntegerField(unique=True)),
                ('acc_type', models.CharField(choices=[('SB', 'Savings Account'), ('CB', 'Current Account')], max_length=2)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.basicdetails')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.loanaccount')),
            ],
        ),
    ]
