# Generated by Django 3.1.1 on 2020-09-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BasicDetails',
            new_name='BasicDetail',
        ),
    ]
